"""
---*** THE PROBLEM ***---
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

---*** SOLUTION NOTES ***---
First, generate the terms below 4,000,000. Then sum those terms that are even.
Terms that are even are perfectly divisible by 2. 64 % 2 = 0 for example.
"""


def is_even(num):
    # 'num' is the term to be tested.
    # Returns True if remainder of 'num/2' is 0.

    if num % 2 == 0:
        return True

    else:
        return False


def generate_fibonacci(upper):
    # 'upper' is the upper bound for the maximum term of the Fibonacci to create, does not create this term.
    # Returns a list with the terms of the sequence.

    # Create variables for the list of terms, the next number to go into the sequence, and an iterative term.
    fibonacci = [1, 2]
    fibonacci_next = 3
    i = 2

    # Iterate whilst the next number in the sequence is less than the requested bound.
    while fibonacci_next < upper:

        # Append the next term of the sequence
        fibonacci.append(fibonacci_next)

        # Find the next term of the sequence (defined in the problem statement as the sum of the previous terms.
        fibonacci_next = fibonacci[i] + fibonacci[i - 1]

        # Increase the iterative term.
        i += 1

    return fibonacci


def sum_of_even_terms(upper):
    # 'upper' is the upper bound for the maximum term of the Fibonacci to create,
    # does not create this term. (used in other function).
    # Returns the sum of the even terms of the Fibonacci sequence below the upper bound specified.

    # Generate the terms of the Fibonacci sequence needed for the solution
    fibonacci = generate_fibonacci(upper)
    addition = 0

    # Iterate over all the terms in the list
    for i in range(0, len(fibonacci)):

        # If an element is even;
        if is_even(fibonacci[i]):

            # Add it to the final answer
            addition += fibonacci[i]

    return addition


# Set program up for the initial conditions specified by the problem.
upper = 4000000

# Find the sum of the even terms
solution = sum_of_even_terms(upper)

# Print the solution
print(solution)
